CREATE TABLE ANOTACAO(
	ID_ANOTACAO INT(11),
	NOME VARCHAR(120) NOT NULL,
	DESCRICAO VARCHAR(120) NOT NULL,
	CONTEUDO TEXT NOT NULL,
		CONSTRAINT PK_ANOTACAO PRIMARY KEY(ID_ANOTACAO)
);

ALTER TABLE anotacao CHANGE ID_ANOTACAO ID_ANOTACAO INT(11) NOT NULL AUTO_INCREMENT;